In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.read_csv("kaggle_diabetes.csv")

In [3]:
df.head(50)

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,2,138,62,35,0,33.6,0.127,47,1
1,0,84,82,31,125,38.2,0.233,23,0
2,0,145,0,0,0,44.2,0.630,31,1
3,0,135,68,42,250,42.3,0.365,24,1
4,1,139,62,41,480,40.7,0.536,21,0
5,0,173,78,32,265,46.5,1.159,58,0
6,4,99,72,17,0,25.6,0.294,28,0
7,8,194,80,0,0,26.1,0.551,67,0
8,2,83,65,28,66,36.8,0.629,24,0
9,2,89,90,30,0,33.5,0.292,42,0
10,4,99,68,38,0,32.8,0.145,33,0
11,4,125,70,18,122,28.9,1.144,45,1
12,3,80,0,0,0,0.0,0.174,22,0
13,6,166,74,0,0,26.6,0.304,66,0
14,5,110,68,0,0,26.0,0.292,30,0
15,2,81,72,15,76,30.1,0.547,25,0
16,7,195,70,33,145,25.1,0.163,55,1
17,6,154,74,32,193,29.3,0.839,39,0
18,2,117,90,19,71,25.2,0.313,21,0
19,3,84,72,32,0,37.2,0.267,28,0
20,6,0,68,41,0,39.0,0.727,41,1
21,7,94,64,25,79,33.3,0.738,41,0
22,3,96,78,39,0,37.3,0.238,40,0
23,10,75,82,0,0,33.3,0.263,38,0
24,0,180,90,26,90,36.5,0.314,35,1
25,1,130,60,23,170,28.6,0.692,21,0
26,2,84,50,23,76,30.4,0.968,21,0
27,8,120,78,0,0,25.0,0.409,64,0
28,12,84,72,31,0,29.7,0.297,46,1
29,0,139,62,17,210,22.1,0.207,21,0
30,9,91,68,0,0,24.2,0.200,58,0
31,2,91,62,0,0,27.3,0.525,22,0
32,3,99,54,19,86,25.6,0.154,24,0
33,3,163,70,18,105,31.6,0.268,28,1
34,10,122,78,31,0,27.6,0.512,45,0
35,4,103,60,33,192,24.0,0.966,33,0
36,11,138,76,0,0,33.2,0.420,35,0
37,9,102,76,37,0,32.9,0.665,46,1
38,2,90,68,42,0,38.2,0.503,27,1
39,4,111,72,47,207,37.1,1.390,56,1
40,3,180,64,25,70,34.0,0.271,26,0
41,7,133,84,0,0,40.2,0.696,37,0
42,7,106,92,18,0,22.7,0.235,48,0
43,9,171,110,24,240,45.4,0.721,54,1
44,7,159,64,0,0,27.4,0.294,40,0
45,0,180,66,39,0,42.0,1.893,25,1
46,1,146,56,0,0,29.7,0.564,29,0
47,2,71,70,27,0,28.0,0.586,22,0
48,7,103,66,32,0,39.1,0.344,31,1
49,7,105,0,0,0,0.0,0.305,24,0

In [4]:
df.describe()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
count,2000.000000,2000.000000,2000.000000,2000.000000,2000.000000,2000.000000,2000.000000,2000.000000,2000.000000
mean,3.703500,121.182500,69.145500,20.935000,80.254000,32.193000,0.470930,33.090500,0.342000
std,3.306063,32.068636,19.188315,16.103243,111.180534,8.149901,0.323553,11.786423,0.474498
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.078000,21.000000,0.000000
25%,1.000000,99.000000,63.500000,0.000000,0.000000,27.375000,0.244000,24.000000,0.000000
50%,3.000000,117.000000,72.000000,23.000000,40.000000,32.300000,0.376000,29.000000,0.000000
75%,6.000000,141.000000,80.000000,32.000000,130.000000,36.800000,0.624000,40.000000,1.000000
max,17.000000,199.000000,122.000000,110.000000,744.000000,80.600000,2.420000,81.000000,1.000000

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2000 entries, 0 to 1999
Data columns (total 9 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Pregnancies               2000 non-null   int64
 1   Glucose                   2000 non-null   int64
 2   BloodPressure             2000 non-null   int64
 3   SkinThickness             2000 non-null   int64
 4   Insulin                   2000 non-null   int64
 5   BMI                       2000 non-null   float64
 6   DiabetesPedigreeFunction  2000 non-null   float64
 7   Age                       2000 non-null   int64
 8   Outcome                   2000 non-null   int64
dtypes: float64(2), int64(7)
memory usage: 140.8 KB

In [6]:
# Replacing the 0 values from ['Glucose','BloodPressure','SkinThickness','Insulin','BMI'] by NaN
df_copy = df.copy(deep=True)
df_copy[['Glucose','BloodPressure','SkinThickness','Insulin','BMI']] = df_copy[['Glucose','BloodPressure','SkinThickness','Insulin','BMI']].replace(0,np.NaN)

In [7]:
# Replacing NaN value by mean, median depending upon distribution
df_copy['Glucose'].fillna(df_copy['Glucose'].mean(), inplace=True)
df_copy['BloodPressure'].fillna(df_copy['BloodPressure'].mean(), inplace=True)
df_copy['SkinThickness'].fillna(df_copy['SkinThickness'].mean(), inplace=True)
df_copy['Insulin'].fillna(df_copy['Insulin'].median(), inplace=True)
df_copy['BMI'].fillna(df_copy['BMI'].mean(), inplace=True)

In [8]:
df_copy.head()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,2,138.0,62.000000,35.000000,126.0,33.6,0.127,47,1
1,0,84.0,82.000000,31.000000,125.0,38.2,0.233,23,0
2,0,145.0,72.403665,29.341275,126.0,44.2,0.630,31,1
3,0,135.0,68.000000,42.000000,250.0,42.3,0.365,24,1
4,1,139.0,62.000000,41.000000,480.0,40.7,0.536,21,0

In [9]:
df = df_copy

In [10]:
df.head()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,2,138.0,62.000000,35.000000,126.0,33.6,0.127,47,1
1,0,84.0,82.000000,31.000000,125.0,38.2,0.233,23,0
2,0,145.0,72.403665,29.341275,126.0,44.2,0.630,31,1
3,0,135.0,68.000000,42.000000,250.0,42.3,0.365,24,1
4,1,139.0,62.000000,41.000000,480.0,40.7,0.536,21,0

In [11]:
df.isnull()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...
1995,False,False,False,False,False,False,False,False,False
1996,False,False,False,False,False,False,False,False,False
1997,False,False,False,False,False,False,False,False,False
1998,False,False,False,False,False,False,False,False,False
1999,False,False,False,False,False,False,False,False,False

In [12]:
df.describe()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
count,2000.000000,2000.000000,2000.000000,2000.000000,2000.00000,2000.000000,2000.000000,2000.000000,2000.000000
mean,3.703500,121.975340,72.403665,29.341275,140.48200,32.650101,0.470930,33.090500,0.342000
std,3.306063,30.533114,11.949531,9.123652,81.56284,7.190136,0.323553,11.786423,0.474498
min,0.000000,44.000000,24.000000,7.000000,14.00000,18.200000,0.078000,21.000000,0.000000
25%,1.000000,99.000000,64.000000,25.000000,120.00000,27.600000,0.244000,24.000000,0.000000
50%,3.000000,118.000000,72.000000,29.341275,126.00000,32.400000,0.376000,29.000000,0.000000
75%,6.000000,141.000000,80.000000,32.000000,130.00000,36.800000,0.624000,40.000000,1.000000
max,17.000000,199.000000,122.000000,110.000000,744.00000,80.600000,2.420000,81.000000,1.000000

In [13]:
# model building

X = df.drop(["Outcome"],axis = 1)
y = df["Outcome"]

In [14]:
X.head()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age
0,2,138.0,62.000000,35.000000,126.0,33.6,0.127,47
1,0,84.0,82.000000,31.000000,125.0,38.2,0.233,23
2,0,145.0,72.403665,29.341275,126.0,44.2,0.630,31
3,0,135.0,68.000000,42.000000,250.0,42.3,0.365,24
4,1,139.0,62.000000,41.000000,480.0,40.7,0.536,21

In [15]:
y.head()

0    1
1    0
2    1
3    1
4    0
Name: Outcome, dtype: int64

In [16]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20, random_state=0)

In [17]:
from sklearn.ensemble import RandomForestClassifier
rf_clf = RandomForestClassifier()

In [18]:
n_estimators = [int(x) for x in np.linspace(start =100,stop=1200,num=12)]
max_features = ['auto','sqrt']
max_depth = [int(x) for x in np.linspace(start =5,stop=30,num=6)]
min_samples_split = [2,5,10,15,100]
min_samples_leaf = [1,2,5,10]

In [19]:
parameters = {"n_estimators":n_estimators,
             "max_features":max_features,
             "max_depth":max_depth,
              "min_samples_split":min_samples_split,
              "min_samples_leaf":min_samples_leaf}
print(parameters)

{'n_estimators': [100, 200, 300, 400, 500, 600, 700, 800, 900, 1000, 1100, 1200], 'max_features': ['auto', 'sqrt'], 'max_depth': [5, 10, 15, 20, 25, 30], 'min_samples_split': [2, 5, 10, 15, 100], 'min_samples_leaf': [1, 2, 5, 10]}

In [20]:
from sklearn.model_selection import RandomizedSearchCV
rf_random = RandomizedSearchCV(rf_clf,parameters,n_iter=10,scoring = "neg_mean_squared_error",n_jobs = -1,cv=5,verbose =2,random_state = 0)

In [21]:
rf_random.fit(X_train,y_train)

Fitting 5 folds for each of 10 candidates, totalling 50 fits

C:\Users\jains\anaconda3\envs\diabetesprediction\lib\site-packages\sklearn\ensemble\_forest.py:427: FutureWarning: `max_features='auto'` has been deprecated in 1.1 and will be removed in 1.3. To keep the past behaviour, explicitly set `max_features='sqrt'` or remove this parameter as it is also the default value for RandomForestClassifiers and ExtraTreesClassifiers.
  warn(

RandomizedSearchCV(cv=5, estimator=RandomForestClassifier(), n_jobs=-1,
                   param_distributions={'max_depth': [5, 10, 15, 20, 25, 30],
                                        'max_features': ['auto', 'sqrt'],
                                        'min_samples_leaf': [1, 2, 5, 10],
                                        'min_samples_split': [2, 5, 10, 15,
                                                              100],
                                        'n_estimators': [100, 200, 300, 400,
                                                         500, 600, 700, 800,
                                                         900, 1000, 1100,
                                                         1200]},
                   random_state=0, scoring='neg_mean_squared_error', verbose=2)

In [22]:
y_test_pred = rf_random.predict(X_test)
y_test_pred

array([0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1,
       0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0,
       1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1,
       0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1,
       1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0,
       0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0,
       1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0,
       1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0,
       1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1,
       0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0,
       1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0,
       0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1,
       0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1,
       1, 1, 1, 0], dtype=int64)

In [23]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_test_pred)

0.96

In [24]:
y_train_pred = rf_random.predict(X_train)

accuracy_score(y_train,y_train_pred)

0.9925

In [25]:
import pickle
file = open("diabetes_prediction_model.pkl",'wb')
pickle.dump(rf_random,file)